# Generated by Django 3.1.4 on 2021-05-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=15)),
                ('email', models.EmailField(max_length=20)),
                ('avail_bal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transectiondetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=15)),
                ('email', models.EmailField(max_length=20)),
                ('deb_cr_amt', models.IntegerField()),
                ('ac_bal', models.IntegerField()),
            ],
        ),
    ]
