# Generated by Django 3.1.4 on 2021-05-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFS', '0002_auto_20210507_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='transectiondetail',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
