# Generated by Django 3.1.4 on 2021-05-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFS', '0003_auto_20210507_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transectiondetail',
            old_name='deb_cr_amt',
            new_name='cr_amt',
        ),
        migrations.AddField(
            model_name='transectiondetail',
            name='deb_amt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
